### ISSUE TITLE
Question/Help - Waiting for call completion?

### ISSUE THREAD

**Issue by senshi-x** [voryx/RxThruwayClient#13]
I have a custom process that runs both RxThruwayClient and bunnyPHP's async client (reactPHP based), using a single eventloop. This process is the business logic serverside and works as a job manager (among other things).

The users will call the job scheduler (rxthruway) and expect a simple result: the id value the generated job will have. But before this can be returned, the rxthruwayclient has to finish making its own RPC call to the internal AuthorizationManager (add_authorization_rule), as the client will then subscribe to that specific topic to receive information about the job status.
How can I implement this?

This is my first project dealing with ReactPHP and Rx/Observable, so I fear I might make very basic mistakes.

Simplified code sample:
```php
        $client->register('example.slowjob', function ($jobdata) {
                $jobid = uniqid();
                $client->call('add_authorization_rule', [(object)[
                    'role'  => 'user',
                    'action'=> 'subscribe',
                    'uri'   => 'example.jobstatus.' . $jobid,
                    'allow' => true
                ]])->subscribe(
                    function (ResultMessage $res) {
                       // This is where the RPC return $jobid should be triggered.
                });
                return $jobid; // this should only be returned after above call is complete. this way, it gets returned too early, leading to the user trying tosubscribe before he is allowed to.
        })->subscribe();
```
The only solution I could come up with was to publish on a different, already-subscribed topic when the add_auth-call is complete, to which the client can then react by subscribing to the new topic. But that seems unnecessarily convoluted, and would make the RPC pointless (as it doesn't return anything of value).
I obviously want to avoid blocking the event loop, but I feel there must be an easier way.

Help would be appreciated!

**Comment by mbonneau** [comment]
@WGPSenshi What is `$client` in your above example?

**Comment by davidwdan** [comment]
@WGPSenshi You should be able to use `concat`, which waits until the lefthand observable completes before emitting the value of the righthand observable:

```PHP
$client->register('example.slowjob', function ($jobdata) use ($client){
    $jobid = uniqid();
    
    return $client->call('add_authorization_rule', [(object)[
        'role'  => 'user',
        'action'=> 'subscribe',
        'uri'   => 'example.jobstatus.' . $jobid,
        'allow' => true
    ]])->concat(Observable::of($jobid));
    
})->subscribe();
```

**Comment by davidwdan** [comment]
You can also just return the observable and map to `$jobid`

```PHP
$client->register('example.slowjob', function ($jobdata) use ($client){
    $jobid = uniqid();
    
    return $client->call('add_authorization_rule', [(object)[
        'role'  => 'user',
        'action'=> 'subscribe',
        'uri'   => 'example.jobstatus.' . $jobid,
        'allow' => true
    ]])->mapTo($jobid);
    
})->subscribe();
```

**Comment by senshi-x** [comment]
@mbonneau : My sample code was malformed, sorry. $client is actually equal to $this->thruway. Either way, it's the RxThruwayClient.

Thanks for the examples, davidwdan. Works just as intended now! One step closer to fully grasping the chaining powers of Rx :) .
