### ISSUE TITLE
Is there a way to make a signle call and return value?

### ISSUE THREAD

**Issue by devicebusy** [voryx/RxThruwayClient#15]

**Comment by mbonneau** [comment]
@devicebusy - Yes.
```php
$wamp->call('add.rpc', [1, 2])->subscribe(function (Thruway\Message\ResultMessage $r) { ... });
```

**Comment by devicebusy** [comment]
Thank you, i've read the docs :), but it doesnt return control. I need to make just one RPC call in some function and continue on my code flow, this example still waits for something.

**Comment by davidwdan** [comment]
@devicebusy `$wamp->call` is asynchronous.  If you want to wait for the result you can use `toPromise` with [await](https://github.com/clue/reactphp-block#await).

```PHP
$promise = $wamp->call('add.rpc', [1, 2])->toPromise();

$loop = EventLoop\getLoop(); // Get the global static loop or use a loop you created

$resultMessage = Block\await($promise, $loop);
```

In this example call only returns one value, so you can use clue's await library.  If you have an observable that returns more than one value, such as a progressive RPC, you'll need to use [RxAwait](https://github.com/rxphp/rxawait) or reduce them down to one value before converting the observable to a promise.

Let me know if that answers your question.
